[package]
name = "mpdris2-rs"
version = "1.1.2"
edition = "2024"
authors = ["Leo Shen <i@szclsya.me>"]
license = "GPL-3.0-or-later"
rust-version = "1.88.0"

[dependencies]
anyhow = "1"
thiserror = "2"
tokio = { version = "1", default-features = false, features = ["rt", "macros"]}
bytes = "1"
futures = "0.3"
futures-util = "0.3"
# Commuicating with D-Bus
zbus = { version = "5", default-features = false, features = ["tokio"] }
zvariant = "5"
# Parsing MPD protocol
nom = "8"
# Creating unique album art filenames
twox-hash = "2"
base32 = "0.5"
# Notification template
humantime = "2"
# Logging
log = "0.4"
colored = "3"
fern = { version = "0.7", features = ["colored"] }
# Signal processing
signal-hook = "0.4"
signal-hook-tokio = { version = "0.4", features = ["futures-v0_3"] }
# Config
argh = "0.1"
dirs = "6"
console-subscriber = { version = "*", optional = true }

[features]
# Used alongside tokio-console
tokio-console = ["dep:console-subscriber"]

[profile.release]
# Optimize for size. This isn't a performance sensitive app
opt-level = "z"
panic = "abort"
lto = true
strip = true
codegen-units = 1
